### PR TITLE
submit week 4 task

### PR DESCRIPTION
**Pull request by Angiemou06**
http://100.20.120.162:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. We have to reject repeated email in sign up procedure.
2. I cannot sign in by email and password which I just signed up successfully.

**Comment by Angiemou06** [comment]
I've solved the problem.
http://100.20.120.162:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
Issues remain.

**Comment by Angiemou06** [comment]
My apologies.
I've solved the problem.
http://100.20.120.162:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
No fix. Test your website ONLINE before re-requesting review? You should try to sign up a new account twice for testing repeating email issue, and try to sign in by your new account to test issue in sign in procedure.

You can try to contact me in discord to discuss anything if any other question.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
