### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Angiemou06**
submit week 3 task.
http://100.20.120.162:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot connect to your server.

**Comment by Angiemou06** [comment]
I've solved the problem.

**Review by cwpeng — CHANGES_REQUESTED** [review]
There are two separating lines with 1px height and light grey color.

**Comment by Angiemou06** [comment]
I've solved the problem.
http://100.20.120.162:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
Color of separating lines should be lighter, align with design.

**Comment by Angiemou06** [comment]
I've solved the problem.
http://100.20.120.162:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
