### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Angiemou06**
submit week 5 task.

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Where is your testing URLs?

**Comment by Angiemou06** [comment]
http://100.20.120.162:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should make sure we redirect user to booking page AFTER completion of add booking API.

**Comment by Angiemou06** [comment]
Hello teacher, I have completed the modification.
I just discovered that all the problems (including last week's problems) came from me closing the connection before closing the cursor.
This result really made me laugh and cry. I actually spent so much time debugging because of this small oversight! !

**Review by cwpeng — CHANGES_REQUESTED** [review]
Good fix. But what I say is all about your frontend procedure, you code in frontend does not make sure redirecting ALWAYS AFTER COMPLETION OF PROCEDURE OF ADDING A BOOKING.

So, sometimes we click booking button, and redirected to booking page, but no booking data there, because booking procedure has not been completed and canceled.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
