### PR TITLE
uploaded week2 homework

### PR DESCRIPTION
**Pull request by Angiemou06**
Submite week2 project.
http://100.20.120.162:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your layout exceeds screen width in any device where screen width<1920px.
2. Cannot scroll MRT list.
3. Don't fix footer in the bottom.

未命名-4

**Comment by Angiemou06** [comment]
I've tried to fix the related issues.
Please check again.
Thank you sincerely.
http://100.20.120.162:3000/

**Comment by cwpeng** [comment]
Re-request review so that I can review for you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Left and right edge of content should align with each other in a centered 1200px frame in any device which screen width>1200px.

**Comment by Angiemou06** [comment]
http://100.20.120.162:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
The same issue remains.

**Comment by Angiemou06** [comment]
I apologize for inconvenience. 
http://100.20.120.162:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
