### PR TITLE
updated homework file.

### PR DESCRIPTION
**Pull request by Angiemou06**
http://100.20.120.162:3000/api/attractions?page=1 
http://100.20.120.162:3000/api/attractions?page=0&keyword=劍潭 
http://100.20.120.162:3000/api/attractions?page=0&keyword=北 
http://100.20.120.162:3000/api/attraction/10
http://100.20.120.162:3000/api/mrts

### CODE REVIEW

**Comment by cwpeng** [comment]
Your server is broken after several requests. Try to figure out the root cause and fix it.

**Comment by Angiemou06** [comment]
I fixed it. Please check again. Thanks you!!

**Review by cwpeng — CHANGES_REQUESTED** [review]
http://100.20.120.162:3000/api/attractions?page=0&keyword=%E5%8C%97 should only contain 12 attraction data. http://100.20.120.162:3000/api/attractions?page=1&keyword=%E5%8C%97 should contain rest 3 attraction data.

Fix this issue and re-request review.

**Comment by cwpeng** [comment]
You can just re-request review without closing pull request. Keep tracking of our conversation is helpful.

**Pull request closed without merging**
